### ISSUE TITLE
Selecionar um caso de uso para ser implementado na SPRINT 1. Redigir os fluxos alternativos do caso de uso selecionado.

### ISSUE THREAD

**Issue by tmsasaki** [marcelloantunes/ppads-projeto-05k-2018s2#2]

**Comment by leemonades** [comment]
Fluxos alternativos redigidos, incluindo fluxo de exceção

**Comment by tmsasaki** [comment]
Detalhar melhor o caso de uso REALIZAR CADASTRO. Detalhar quais são os dados que o usuário irá fornecer. Definir quais critérios serão utilizados para considerar os dados válidos ou não.

**Comment by leemonades** [comment]
Done

**Comment by tmsasaki** [comment]
Sugestão: colocar como fluxos alternativos o preenchimento de informações que são opcionais e informações do PET.

**Comment by leemonades** [comment]
Done

**Comment by tmsasaki** [comment]
Sugestão: não é necessário colocar nos casos de uso detalhes de implementação como o uso de expressões regulares ou a criação de chave primária.
