### ISSUE TITLE
Postar o script de criação da base de dados da SPRINT 1. Data: 13/9.

### ISSUE THREAD

**Issue by tmsasaki** [marcelloantunes/ppads-projeto-05k-2018s2#7]

**Comment by marcello-ants** [comment]
A collection é criada a partir de um arquivo qualquer no diretório 'models' da aplicação, como o exemplo em anexo (users.js), automaticamente a partir do Mongoose. O que adiciona cada usuário ao Mongo no momento de cadastro é o código abaixo, em outro arquivo users.js no diretório 'routes' :

User.findOne({ username: { 
			"$regex": "^" + username + "\\b", "$options": "i"
	}}, function (err, user) {
			User.findOne({ email: { 
				"$regex": "^" + email + "\\b", "$options": "i"
		}}, function (err, mail) {
				if (user || mail) {
					res.render('login', {
						user: user,
						mail: mail
					});
				}
				else {
					var newUser = new User({
						name: name,
						email: email,
						username: username,
						password: password,
						petName: petName,
						petGroup: petGroup
					});
					User.createUser(newUser, function (err, user) {
						if (err) throw err;
						console.log(user);
					});
         	req.flash('success_msg', 'Cadastro feito com sucesso');
					res.redirect('/users/login');
				}
			});
		});

[script.zip](https://github.com/marcelloantunes/ppads-projeto-05k-2018s2/files/2402420/script.zip)
