### ISSUE TITLE
Selecionar um caso de uso para implementar na SPRINT 2. Escrever os fluxos alternativos deste caso de uso. Escrever um plano de testes (criar um arquivo plano-de-testes.md na pasta docs).

### ISSUE THREAD

**Issue by tmsasaki** [marcelloantunes/ppads-projeto-05k-2018s2#8]

**Comment by tmsasaki** [comment]
No plano de testes:

* Escrever qual é o resultado esperado com base nos dados de testes (por exemplo, quais serão os nomes dos veterinários que aparecerão como resultado?).

* Escrever testes para todos os fluxos (principal e alternativos).

**Comment by leemonades** [comment]
Professor, o caso de uso a ser implementado na Sprint 2 é o CDU003.

Abraços,

**Comment by leemonades** [comment]
Mudança de planos, será o CDU002.

**Comment by tmsasaki** [comment]
Voltar o texto do caso de uso PROCURAR VETERINÁRIOS no documento casos-de-uso.md
